name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /usr/share/nginx/html/obituary

            # pull latest code, install dependencies, and restart app
            git reset --hard
            git pull origin main
            yarn
            pm2 stop obituary
            pm2 delete obituary
            yarn deploy